# -*- coding: utf-8 -*-
"""EjercicioPiton07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13XvYEwlOOp7Axgw84Z6t1RqWcPRuI1ug
"""

print('Suma y producto de números intermedios')
print('Se debe cumplir a < b')
nUno=int(input("Ingresa el primer número entero positivo (a): "))
nDos=int(input("Ingresa el segundo número entero positivo (b): "))

if (nUno <= 0) or (nDos <= 0) or (nUno >= nDos):
  print('El valor ingresado no es el pedido')

else:
  suma=0
  producto=1
  for i in range(nUno,nDos+1,1):
    suma=i+suma
    producto=i*producto
  print(f'La suma de los números intermedios de {nUno} a {nDos} es: {suma}')
  print(f'El producto de los números intermedios de {nUno} a {nDos} es: {producto}')