# -*- coding: utf-8 -*-
"""EjercicioPiton08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vgjuoM-NMKI2lFmXWQiLdyqqh2GFaRJe
"""

print('Invertir un número')
N=int(input("Ingresa el número entero positivo: "))

if N <= 0:
  print('El valor ingresado no es el pedido')

else:
  NStr=str(N)
  nInvertido=NStr[::-1]
  print(f'El número invertido de {N} es: {nInvertido}')