# -*- coding: utf-8 -*-
"""EjercicioPiton026.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZaDH72AOxoWaVbJccXdwKTFn1zx7iMeP
"""

print('Cifrado César')
texto=input("Ingresa el texto: ")
N=int(input("Posiciones a recorrer: "))
print('')
if (len(texto) < 1) or (N<=1):
  print('Los valores no son los pedidos')
else:
  cifrad=''
  abc='AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz'
  for c in texto:
    if c in abc:
      cifrad += abc[(abc.index(c)+(N*2)) % (len(abc))]
    else:
      cifrad += c
  print(f'El texto cifrado es: {cifrad}')