# -*- coding: utf-8 -*-
"""EjercicioPiton04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n3Bl2nPclW-ioaZpfQrKX30ywZoGXf-H
"""

print('Triángulo de números')
N=int(input("Ingresa el número de filas: "))

if N <= 0:
  print('El valor ingresado no es el pedido')
else:
  for i in range(1,N+1,1):
    for j in range((i*2)-1,0,-2):
      print(f'{j}', end=" ")
    print(" ")