# -*- coding: utf-8 -*-
"""EjercicioPiton028.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p2xUHBuX-f4alaKCmOppzVnHG1eB2TVy
"""

print('Promedio y desviación estándar')
accion=True
nList=[]
while accion:
  N=float(input("Agrega un número: "))
  comand=input("Desea agregar mas valores (Y o N): ")
  if comand == 'N':
    print('')
    nList.append(N)
    print(f'Número de datos ingresados: {len(nList)}')
    valor=0.0
    valorDos=0.0
    for i in range(0,len(nList),1):
      valor=nList[i]+valor
    promedio=valor/len(nList)
    promedio=round(promedio,5)
    print(f'Promedio: {promedio}')
    for j in range(0,len(nList),1):
      cuadrado=(nList[j] - promedio)**2
      valorDos=cuadrado + valorDos
    desEstandar = pow((valorDos/len(nList)),0.5)
    desEstandar = round(desEstandar,5)
    print(f'Desviación estándar: {desEstandar}')
    break
  elif comand == 'Y':
    nList.append(N)
    continue
  else:
    print('Valor no pedido')
    continue