# -*- coding: utf-8 -*-
"""EjercicioPiton022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CZ_I0UY0IOSqCe6eGe_g-uVr82zGJRXW
"""

print('Números primos')
N=int(input("Ingresa hasta que números primos quieres visualizar: "))
print('')
if (N<=1):
  print('Los valores no son los pedidos')
if N > 1:
  print(f'Los números primos hasta el {N} son: 2',end='')
if N>2:
  print(', ', end='')
  evaluar=[]
  for i in range(1,int(N/4),1):
    for j in range(1,int(N/4),1):
      valor= i + j + 2 * i * j
      evaluar.append(valor)
  resultado=[k for k in range(1,N+1,1)]
  for l in range(0,len(evaluar),1):
    for m in range(0,len(resultado)-1,1):
      if evaluar[l] == resultado[m]:
        resultado.remove(evaluar[l])
  primos=[]
  for o in range(0,len(resultado),1):
    final=0
    final = (resultado[o]*2)+1
    if final > N:
      break
    else:
      primos.append(final)
  for p in range(0,len(primos)-1,1):
    print(f'{primos[p]}, ',end='')
  print(primos[len(primos)-1])