# -*- coding: utf-8 -*-
"""EjercicioPiton06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zZX-a8G2V2CckptCNlCM2KsD9Lb_3PqG
"""

print('Representación de las unidades, decenas, centenas, ..., de un número.')
N=int(input("Ingresa un número entero positivo: "))

if N <= 0 :
  print('El valor ingresado no es el pedido')
else:
  NStr=str(N)
  NTamaño=len(NStr)
  nInvertido=NStr[::-1]
  multiplicador=1
  valores=[]
  for i in nInvertido:
    valor=int(i)*multiplicador
    multiplicador=multiplicador*10
    valores.append(valor)
  sumaList=valores[::-1]
  print(f'La representación de {N} es: ',end='')
  for j in range(0,NTamaño-1,1):
    print(sumaList[j],end=' + ')
  print(sumaList[NTamaño-1])