# -*- coding: utf-8 -*-
"""EjercicioPiton01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OcXEc5WrJOoQa6Ow--OMB2P5mGZilsuY
"""

print('Valor par o impar')
N=int(input("Agrega un valor entero positivo: "))
if N <= 0:
  print('El valor ingresado no es el pedido')
else:
  if N % 2 == 0:
    print(f'EL número {N} es par')
  else:
    print(f'El número {N} es impar')