# -*- coding: utf-8 -*-
"""EjercicioPiton023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11OuqMNLAHYKaY2NxWPHV709E7e4oiSas
"""

print('Ordenar el texto alfabéticamente directa o inversa')
texto=input("Ingresa el texto: ")
accion=input("Ingrese si el orden será directa (D) o inversa (I): ")
print('')

if (len(texto) <= 1):
  print('El valor ingresado no es el pedido')
elif (accion != 'D') and (accion !='I'):
  print('El valor ingresado no es el pedido')
else:
  textoMinuscula=texto.lower()
  textoDos=textoMinuscula.replace(" ", "")
  textoList=[i for i in textoDos]
  final=[]
  abecedario=[chr(j) for j in range(ord('a'),ord('z')+1)]
  for k in range(0,len(abecedario),1):
    letraUno=abecedario[k]
    for l in range(0,len(textoList),1):
      letraDos=textoList[l]
      if (letraUno==letraDos):
        final.append(letraDos)
  if(accion =='D'):
    print('El texto ordenado alfabéticamente es: ',end='')
    for m in range(0,len(textoList)-1,1):
      print(f'{final[m]}, ',end='')
    print(final[len(textoList)-1])
  elif(accion == 'I'):
    print('El texto ordenado alfabéticamente es: ',end='')
    for m in range(len(textoList)-1,0,-1):
      print(f'{final[m]}, ',end='')
    print(final[0])

