# -*- coding: utf-8 -*-
"""EjercicioPiton09.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Lq1xX7RzweEjmqxnVhazLlAO10AeZic
"""

print('Suma de los digitos de un número')
N=int(input("Ingresa el número entero positivo: "))

if N <= 0:
  print('El valor ingresado no es el pedido')

else:
  NStr=str(N)
  tamaño=len(NStr)
  suma=0
  valores=[]
  for i in (NStr):
    valores.append(i)
  for j in range(0,tamaño,1):
    suma=int(valores[j])+suma
  print(f'La suma de los digitos del número {N} es: {suma}')