# -*- coding: utf-8 -*-
"""EjercicioPiton030.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YvOI4vNxgo_ZBBi5m32purQUVD3vLa5K
"""

import itertools
print('Permutaciones')
N=int(input("Ingresa el número valores a tomar en cuenta (2-6): "))
print('')
if N<2 or N>6:
  print('El valor no es el pedido')
else:
  lista=[]
  for i in range(1,N+1,1):
    valor=input(f'Ingresa el valor {i}: ')
    lista.append(valor)
  permutaciones=list(itertools.permutations(lista))
  print('')
  for j in range(0,len(permutaciones),1):
    print(f'Permutación {j+1}: {permutaciones[j]}')