# -*- coding: utf-8 -*-
"""EjercicioPiton03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KkRu3Z7Wfn4X63JXuouPXY4jjmfjoL1Y
"""

print('Año bisiesto')
N=int(input("Ingresa el año: "))
if N <= 0:
  print('El valor ingresado no es el pedido')
else:
  if N % 4 == 0:
    if ((N % 100 == 0) and (N % 400 == 0)):
       print(f'El año {N} es bisiesto')
    elif ((N % 100 == 0) and (N % 400 != 0)):
      print(f'El año {N} no es bisiesto')
    else:
      print(f'El año {N} es bisiesto')
  else:
    print(f'El año {N} no es bisiesto')