# -*- coding: utf-8 -*-
"""EjercicioPiton018.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vzl-arz464LlM_lrLHWNWe3Y7er3Udwt
"""

print('Convertir un número dentro del rango del 1-3999 a su representación en romano')
N=int(input("Ingresa el valor a representar: "))
print('')

if (N <= 0) or (N > 3999):
  print('El valor ingresado no es el pedido')
else:
  valor=N
  numeros=[1000,900,500,400,100,90,50,40,10,9,5,4,1]
  numerales=['M','CM','D','CD','C','XC','L','XL','X','IX','V','IV','I']
  numeral=''
  i = 0

  while N > 0:
    for _ in range(N // numeros[i]):
      numeral += numerales[i]
      N -= numeros[i]
    
    i += 1
  print(f'La representación del número {valor} en romano es: ',end='')
  print(numeral)