# -*- coding: utf-8 -*-
"""EjercicioPiton024.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qMz3x8XlzYNTUNAX6f5yWG4NjqIQt2Nj
"""

print('Imprimir la frase en cada línea eliminando los espacios')
N=input("Ingresa el texto (no mas de 100 caracteres): ")
print('')

if len(N) <= 1 or len(N)>100:
  print('El valor ingresado no es el pedido')
else:
  nList=N.split()
  for i in range(len(nList)-1,-1,-1):
    for j in range(0,len(nList),1):
      print(nList[j],end=' ')
    print('')
    nList.pop(i)