# -*- coding: utf-8 -*-
"""EjercicioPiton013.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e6PldOmeYQPjW1bmjyaww7mpl0OQsr0o
"""

print('Serie de Padovan')
N=int(input("Ingresa el número de valores a generar: "))

if N <= 0:
  print('El valor ingresado no es el pedido')
else:
  a=1
  b=1
  c=1
  i=3
  print(f'Los primeros {N} valores de la serie son:')
  if N>=1:
    print('1',end='')
  if N>=2:
    print(', 1',end='')
  if N>=3:
    print(', 1',end='')
  while (i<N):
    d=a+b
    a=b
    b=c
    c=d
    i=i+1
    print(f', {d}',end='')