# -*- coding: utf-8 -*-
"""EjercicioPiton017.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a_rtHIrJv9hGkV0bfoGfe0tQDOwB7Dvw
"""

print('Número de Keith')
N=int(input("Ingresa la cantidad de números de Keith a general: "))
print('')

if N <= 0:
  print('Los valores no son los pedidos')
else:
  print('Los números de Keith son: ',end='')
  i=10
  control=True
  valores=[]
  while control==True:
    numero=[j for j in str(i)]
    tamaño=len(numero)
    l=0
    suma=0
    while control==True:
      for k in range(l,tamaño,1):
        suma=suma + int(numero[k])
      if suma==i:
        valores.append(i)
        break
      elif suma > i:
        break
      else:
        numero.append(suma)
        suma=0
        l += 1
        tamaño += 1
    if len(valores) >= N:
      break
    else:
      i += 1
  for m in range(0,len(valores)-1,1):
    print(f'{valores[m]}, ',end='')
  print(valores[len(valores)-1])