# -*- coding: utf-8 -*-
"""EjercicioPiton014.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wlOt1hwbMzqsH1B2kFDpsdek9H70t8wX
"""

print('Números pseudoaleatorios')
n=int(input("Ingresa la cantidad de números aleatorios: "))
a=int(input("Ingresa el valor del multiplicador: "))
b=int(input("Ingresa el valor del sesgo: "))
m=int(input("Ingresa el valor del módulo: "))

if (n <= 0) or (a <= 0) or (b<=0) or (m<=0):
  print('\nEl valor ingresado no es el pedido')
else:
  x=n
  Xn=[]
  X=[]
  Un=[]
  for i in range(0,n,1):
    Xn.append(x)
    valorX=((a*x)+b) % m
    X.append(valorX)
    valorU=x/m
    Un.append(valorU)
    x=valorX
  N=[j for j in range(1,n+1,1)]
  print('')
  print('     n     |     Xn    |    Xn+1    |    Un')
  print('-------------------------------------------------')
  for k in range(0,n,1):
    print(f'     {N[k]}     |     {Xn[k]}     |     {X[k]}     |  {Un[k]:.4f}')