# -*- coding: utf-8 -*-
"""EjercicioPiton020.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LCL-NyIqHCv6suOc8NqwFlUvcavl_A2Z
"""

print('Obten el valor de pi/4 por medio de fracciones continuas')
N=int(input("Ingresa el numero de fracciones que deseas que se hagan: "))
print('')

if N <= 0:
  print('El valor ingresado no es el pedido')

elif N==1:
  print('El resultado es: 1')
elif N==2:
  print('El resultado es: 0.8')
else:
  suma=1
  N=N-1
  for i in range(2,N+1,1):
    suma = suma + 2
  ultDenominador=(N+1)**2
  penultDenominador=ultDenominador - (float(suma)+2)
  for j in range(N,1,-1):
    primResultado=float(penultDenominador)/float(ultDenominador)
    ultDenominador=primResultado +  float(suma)
    penultDenominador=penultDenominador - suma
    suma=suma-2
  aux=(1/ultDenominador) +1
  resultado=1 / aux
  print(f'El resultado es: {resultado}')