# -*- coding: utf-8 -*-
"""EjercicioPiton02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DQRFd9UEB3bXdOy3eXC66lhWLAkrBoth
"""

print('Tabla de multiplicar')
N=int(input("Ingresa un número entero positivo: "))
valores={}

if N <= 0:
  print('El valor ingresado no es el pedido')
else:
  for i in range(1,11,1):
    valor=i*N
    valores[i]=valor
  print(f'Tabla de multiplicar del número {N}')
  print('---------------------------------')
  print('  Multiplicador  |     Producto')
  print('---------------------------------')
  for x in valores:
    print(f'        {x}        |        {valores[x]}')