# -*- coding: utf-8 -*-
"""EjercicioPiton05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z6XII9fxZ1KMQW9ipF0SeepUf_AKP-e9
"""

from math import factorial
print('Cifrado César')
N=int(input("Posiciones a recorrer: "))
print('')
if N<=0:
  print('Los valores no son los pedidos')
else:
  espacios=N
  for i in range(0,N,1):
    for k in range(espacios+1,0,-1):
      print(' ',end='')
    for j in range(0,i+1,1):
      c = int((factorial(i)) / ((factorial(j)) * (factorial(i-j))))
      print(c,end=' ')
    print('')
    espacios -= 1