# -*- coding: utf-8 -*-
"""EjercicioPiton029.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Mg4_F8tot_JkvLRqnsN7O_FvoIHNe-r
"""

import math
import cmath
import numpy
print('Calculadora de números complejos')
N=int(input("¿Cuantos números complejos se van a agregar? (1 o 2): "))
print('')

if N<1 or N>2:
  print('Los valores no son los pedidos')
elif N==1:
  complejo=complex(input('Ingresa el número complejo (a + bj): '))
  accion=input('¿Qué se quiere obtener?\nReal, imaginario, modulo o fase: ')
  print('')
  if accion.lower() == 'real':
    real=complejo.real
    print(f'La parte real del número complejo {complejo} es: {real}')
  elif accion.lower() == 'imaginario':
    imaginario=complejo.imag
    print(f'La parte imaginaria del número complejo {complejo} es: {imaginario}')
  elif accion.lower() == 'modulo':
    modulo=abs(complejo)
    print(f'El modulo del número complejo {complejo} es: {modulo}')
  elif accion.lower() == 'fase':
    faseRad=cmath.phase(complejo)
    fase=(faseRad * 180)/math.pi
    print(f'La fase del número complejo {complejo}: {fase}')
  else:
    print('Valor no pedido')
elif N==2:
  complejoUno=complex(input('Ingresa el primer número complejo (a + bj): '))
  complejoDos=complex(input('Ingresa el segundo número complejo (a + bj): '))
  accion=input('¿Qué se quiere obtener?\nSuma, resta, multiplicacion, division o escalar: ')
  print('')
  if accion.lower() == 'suma':
    suma=complejoUno + complejoDos
    print(f'La suma de {complejoUno} mas {complejoDos} es: {suma}')
  elif accion.lower() == 'resta':
    resta= complejoUno - complejoDos
    print(f'La resta de {complejoUno} menos {complejoDos} es: {resta}')
  elif accion.lower() == 'multiplicacion':
    multiplicacion = complejoUno * complejoDos
    print(f'La multiplicación de {complejoUno} por {complejoDos} es: {multiplicacion}')
  elif accion.lower() == 'division':
    division = complejoUno / complejoDos
    print(f'La división de {complejoUno} entre {complejoDos} es: {division}')
  elif accion.lower() == 'escalar':
    escalar=numpy.vdot(complejoUno,complejoDos)
    print(f'El producto escalar de {complejoUno} y {complejoDos} es: {escalar}')
  else:
    print('Valor no pedido')
else:
  print('Los valores no son los pedidos')