# -*- coding: utf-8 -*-
"""EjercicioPiton025.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11osFkp653M2litQnwkcJgY0sevg29_rn
"""

print('Imprimir la frase en cada línea eliminando los espacios')
N=input("Ingresa el texto (no mas de 100 caracteres): ")
print('')

if len(N) <= 1:
  print('El valor ingresado no es el pedido')
else:
  texto=N.lower()
  abc=[chr(i) for i in range(ord('a'),ord('z')+1)]
  for j in range(0,len(abc),1):
    evaluar=abc[j]
    print(f'La frecuencia de {evaluar} en el texto es de: ',texto.count(evaluar))