# -*- coding: utf-8 -*-
"""EjercicioPiton011.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NTLl0E8Xyc7kPzffC2eKU9DJWTfQpRnp
"""

print('Codigo EAN-8')
N=int(input("Ingresa el valor de 8 dígitos: "))

NStr=str(N)
NTamaño=len(NStr)

if NTamaño != 8:
  print('El valor ingresado no es el pedido')
else:
  NList=[i for i in NStr]
  listaFinal=[]
  sumaImpares=0
  sumaPares=0
  for j in range(0,8,2):
    sumaImpares=sumaImpares+int(NList[j])
  for k in range(1,9,2):
    sumaPares=sumaPares+int(NList[k])
  segundo=sumaPares * 3
  tercero=segundo + sumaImpares
  cuarto=tercero % 10
  valorFinal=10 - cuarto
  listaFinal=NList
  listaFinal.append(str(valorFinal))
  print('El codigo EAN-8 es: ',end="")
  for l in listaFinal:
    print(l , end='')