# -*- coding: utf-8 -*-
"""EjercicioPiton019.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mICLjllvDjlK9ACA6GF1nfcRn-Ei3mUi
"""

print('Números de Pell')
N=int(input("Ingresa el número de valores a mostrar: "))
print('')

if (N <= 0):
  print('El valor ingresado no es el pedido')
else:
  print(f'Los primeros {N} números de Pell son:')
  if (N>=1):
    print('0',end='')
  if (N>=2):
    print(', 1',end='')
  n1=0
  n2=1
  for i in range(0,N-2,1):
    aux=n2
    n2= n1 + (2*n2)
    n1=aux
    print(f', {n2}',end='')