# -*- coding: utf-8 -*-
"""EjercicioPiton027.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qgr3JO2wtM0Ivt2sNoa9EbqcYUoX5v5X
"""

print('Detectar si una palabra o frase es palíndromo')
N=input("Ingresa el texto: ")
print('')

if len(N) <= 1:
  print('El valor ingresado no es el pedido')

else:
  nMinuscula=N.lower()
  palindromo=nMinuscula.replace(" ", "")
  nInvertido=palindromo[::-1]
  if nInvertido==palindromo:
    print(f'{N} es palíndromo')
  else:
    print(f'{N} no es un palíndromo')