# -*- coding: utf-8 -*-
"""EjercicioPiton012.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Sw4oAvY3G-1eBfyVnKIjBF3o5mUhW-Z
"""

print('Abecedario')
abecedarioList=[]
abecedarioListDos=[]
for i in range(97,123):
  abecedarioList.append(chr(i))
abecedario=''.join(abecedarioList)
for j,val in enumerate(abecedario):
  if (j+1) % 3 != 0:
    abecedarioListDos.append(val)
print(f'Abecedario: {abecedarioList}')
print(f'Abecedario sin letras: {abecedarioListDos}')